import Main from "./Containers/Main";
import Payment from "./Containers/Pages/Payment";
import Signup from "./Containers/Pages/Signup";
import Login from "./Containers/Pages/Login";
import Account from "./Containers/Pages/Account";
import Admin from "./Containers/Content/Admin";
import Video from "./Containers/Content/VideoPage";
import Girl from "./Containers/Content/GirlPage";
import Girls from "./Containers/Content/Girls";
